nome=str(input("Digite seu nome: ").strip())
letras=len(nome)-nome.count(" ")
maiuscula= nome.upper()
minuscula= nome.lower()
pnnome= nome.find(" ")
pnome= nome.split()
print(F"Seu nome em maiusculo: {maiuscula}")
print(f"Seu nome em minuscula: {minuscula}")
print (f"Seu nome ao todo tem {letras}")
print (f"Seu primeiro nome é: {pnome}")
print(f"Seu primeiro nome tem {pnnome}")
