nome=(input("Digite seu nome: "))
print ("Analisando seu nome...")
print("_"*50)
print ("Seu nome em Maisculo fica "+nome.upper())
print ("Seu nome em minusculo fica "+nome.lower())
print (f"Seu nome contém ao todo {(len(nome))} letras")
print (f"Seu primeiro nome é {nome.split()}")
print (f"Seu primeiro nome tem {nome.find(" ")} letras")
print("_"*50)